version: 2
updates:
  - package-ecosystem: "bundler"
    directory: /
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Australia/Brisbane"
    # Labels on pull requests for version updates only
    labels:
      - "gem dependencies"
