---
inherit_gem:
  aaf-gumboot: aaf-rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*

AbcSize:
  Exclude:
    - lib/metadata/**/*

ClassLength:
  Exclude:
    - lib/metadata/saml.rb

MethodLength:
  Exclude:
    - lib/metadata/saml.rb

CyclomaticComplexity:
  Exclude:
    - lib/metadata/saml.rb

PerceivedComplexity:
  Exclude:
    - lib/metadata/saml.rb
