require: rubocop-rails

inherit_from:
  - https://raw.githubusercontent.com/ausaccessfed/aaf-gumboot/develop/aaf-rubocop.yml

AllCops:
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Exclude:
    - lib/metadata/**/*

Metrics/ClassLength:
  Exclude:
    - lib/metadata/saml.rb

Metrics/MethodLength:
  Exclude:
    - lib/metadata/saml.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/metadata/saml.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/metadata/saml.rb

Metrics/BlockLength:
  Exclude:
    - lib/metadata/saml.rb
    - spec/**/*.rb
    - lib/tasks/*.rake
    - config/**/*.rb
    - db/**/*.rb

# List duplicated from here, but with `touch` removed:
# https://github.com/bbatsov/rubocop/blob/863037ac719d3539c1dd7e7f7715915f5b612c93/config/default.yml#L1539-L1551
Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - update_all
    - update_attribute
    - update_column
    - update_columns
    - update_counters

Rails/FindEach:
  Enabled: false

Style/RescueStandardError:
  Exclude:
    - spec/controllers/api/raw_entity_descriptors_controller_spec.rb
    - spec/jobs/update_entity_source_spec.rb

Lint/UriEscapeUnescape:
  Exclude:
    - spec/routes/metadata_query_controller_spec.rb

Naming/MethodParameterName:
  Enabled: false
