# No need for API documentation.
Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/initializers/secret_token.rb
    - db/**/*
    - Guardfile

AbcSize:
  Exclude:
    - lib/metadata/**/*

ClassLength:
  Exclude:
    - lib/metadata/saml.rb

MethodLength:
  Exclude:
    - lib/metadata/saml.rb

CyclomaticComplexity:
  Exclude:
    - lib/metadata/saml.rb

PerceivedComplexity:
  Exclude:
    - lib/metadata/saml.rb
