language: ruby
rvm:
  - 2.1.1
branches:
  only:
    - master
    - develop
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - mysql -e 'create database saml_test;'
  - RAILS_ENV=test bundle exec rake --trace db:migrate