default: &default
  adapter: mysql2
  encoding: utf8
  username: saml_app
  password: password
  host: 127.0.0.1
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: saml_development

test:
  <<: *default
  database:
    <%= if ENV['TEST_ENV_NUMBER']
          "test#{ENV['TEST_ENV_NUMBER']}"
        else
          'saml_test'
        end %>
  username: <%= ENV['MYSQL_USER'] || 'saml_app' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
  host: localhost

production:
  <<: *default
  username: <%= ENV['SAML_DB_USERNAME'] %>
  password: <%= ENV['SAML_DB_PASSWORD'] %>
  database: <%= ENV['SAML_DB_NAME'] %>
