default: &default
  adapter: mysql2
  username: <%= ENV['SAML_DB_USERNAME'] || saml_app %>
  password: <%= ENV['SAML_DB_PASSWORD'] || password %>
  host: <%= ENV['SAML_DB_HOST'] || 127.0.0.1 %>
  port: <%= ENV['SAML_DB_PORT'] || 3306 %>
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_bin
  sql_mode: TRADITIONAL

development:
  <<: *default
  database: <%= ENV['SAML_DB_NAME'] || saml_development %>

test:
  <<: *default
  database: <%= ENV['SAML_DB_NAME'] || saml_test %>

production:
  <<: *default
  username: <%= ENV['SAML_DB_USERNAME'] %>
  password: <%= ENV['SAML_DB_PASSWORD'] %>
  database: <%= ENV['SAML_DB_NAME'] %>
  host: <%= ENV['SAML_DB_HOST'] %>
  port: <%= ENV['SAML_DB_PORT'] %>
