name: Build Docker Image
on:
  push:
  issue_comment:
    types: [created]
jobs:
  push:
    concurrency:
      group: ${{ github.event_name }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}-build
      cancel-in-progress: true
    name: Test, build and push image
    permissions:
      id-token: write
      contents: read
      statuses: write
      pull-requests: write
    secrets: inherit
    uses: ausaccessfed/workflows/.github/workflows/deploy-sync.yml@main
    with:
      ecr_repository: saml-service
      dev_url: https://saml.dev.aaf.edu.au
      event_name: ${{ github.event_name }}
      event_comment_id: ${{ github.event.comment.id }}
      event_comment_body: ${{ github.event.comment.body }}
      production_environments: "test,production"
      extra_task_1_name: Tests
      extra_task_1: docker run --env-file=.env.test.dist --add-host=host.docker.internal:host-gateway -e SAML_DB_HOST=host.docker.internal -e PREPARE_DB=true -e SAML_DB_USERNAME=root -e SAML_DB_PASSWORD=password app:cache bundle exec rspec
      extra_task_2_name: rubocop
      extra_task_2: docker run app:cache bundle exec rubocop -P
      extra_task_3_name: brakeman
      extra_task_3: docker run app:cache bundle exec brakeman
